routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => 'web'], function () {

        // 'middleware' => 'admin'
        Route::group(['prefix' => 'admin'], function () {

            Route::resource('/pensionato', 'BoardingSchoolController');
            Route::resource('/responsavel', 'ResponsableController');
            Route::resource('/pensionista', 'BoarderController');
            Route::resource('/quartos', 'BedroomController');
            Route::resource('/contrato', 'ContractController');
            Route::resource('/gastos-mensais', 'MonthlyBillController');
            Route::resource('/melhorias', 'ImprovementController');
            Route::resource('/funcionario', 'EmployeeController');
            Route::resource('/tarefas', 'TaskController');
            Route::resource('/contato', 'ContactController');
            Route::resource('/usuario', 'UserController');
            Route::resource('/regras', 'RuleController');

            Route::get('/melhorias-completas', 'ImprovementController@completed')->name('melhorias.completed');
            Route::get('/melhorias/to-complete/{id}', 'ImprovementController@complete')->name('melhorias.complete');
            Route::get('/melhorias-aprovadas', 'ImprovementController@approved')->name('melhorias.approved');
            Route::get('/melhorias/nao/aprovadas', 'ImprovementController@desaproved')->name('melhorias.desaproved');
            Route::get('/melhorias/to-approve/{id}', 'ImprovementController@approve')->name('melhorias.to.approve');
            Route::post('/melhorias/to-desaprove/{id}', 'ImprovementController@desapprove')->name('melhorias.to.desapprove');
            Route::get('/melhorias/check-duplication/{name}', 'ImprovementController@checkDuplication')->name('melhorias.check-duplication');

            Route::get('/home/pensionato', 'BoardingSchoolController@home')->name('boarding.home');

            Route::get('/configuracoes', 'ConfigController@create')->name('system.config');
            Route::get('/configuracoes/show/', 'ConfigController@show')->name('system.config.show');
            Route::post('/configuracoes/store', 'ConfigController@store')->name('system.config.store');
            Route::get('/configuracoes/edit/{id}', 'ConfigController@edit')->name('system.config.edit');
            Route::put('/configuracoes/update/{id}', 'ConfigController@update')->name('system.config.update');

            Route::get('/mensalidades', 'PaymentController@index')->name('payment.index');
            Route::get('/mensalidades/show/{id}', 'PaymentController@show')->name('payment.show');
            Route::get('/gerar', 'PaymentController@generate')->name('payment.generate');
        });


        //MIDDLEWARE PENSIONISTA
        Route::group(['middleware' => 'boarder', 'prefix' => 'pensionista'], function () {

        });

        //'middleware' => 'employee',
        //MIDDLEWARE FUNCIONÁRIO
        Route::group(['prefix' => 'funcionario'], function () {
            Route::get('/tarefas', 'EmployeeController@listTasksOfEmployee')->name('tasks.employee');
        });



        Route::get('/home', 'DashboardController@index')->name('home');
        Route::get('/modal', 'Controller@modal')->name('modal');
        Route::get('/modal/improvement', 'Controller@modalImprovement')->name('modal.improvement');
        Route::get('/modal/completed', 'Controller@modalCompleted')->name('modal.completed');
    });

});

Auth::routes();
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', function () {
    return redirect('/login');
});

app/Models/Responsable.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Responsable extends Model
{
    protected $fillable = ['name', 'cpf', 'rg', 'phone', 'facebook', 'whatsapp', 'email', 'status', 'addresses_id'];

    public function user()
    {
        return $this->belongsToMany('App\Models\User', 'responsables_has_users', 'responsables_id', 'users_id')->where('status', 1);
    }

    public function address()
    {
        return $this->belongsTo('App\Models\Address', 'addresses_id')->where('status', 1);
    }

    public function boarding_school()
    {
        return $this->hasMany('App\Models\BoardingSchool', 'responsables_id')->where('status', 1);
    }

    public function boarders()
    {
        return $this->hasMany('App\Models\Boarder', 'responsables_id')->where('status', 1);
    }
}

app/Http/Controllers/ResponsableController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ResponsableRequest;
use App\Repositories\ResponsableRepository;
use App\Models\Responsable;

class ResponsableController extends Controller
{
    private $responsable;

    public function __construct(Request $request)
    {
        $this->responsable = new ResponsableRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $responsables = $this->responsable->index();
            return view('admin.responsables.index', compact('responsables'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {

            $data = $this->responsable->create();
            $boarding_schools = $data[0];
            $boarders = $data[1];
            $users = $data[2];

            return view('admin.responsables.create', compact('boarding_schools', 'boarders', 'users'));

        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ResponsableRequest $request)
    {
        try {
            $this->responsable->store($request);
            return redirect()->route('responsavel.index')->with('status', 'success')->with('message', 'Responsável criado com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data =  $this->responsable->edit($id);

            $responsable = $data[0];
            $boarding_schools = $data[1];
            $boarders = $data[2];
            $users = $data[3];

            return view('admin.responsables.edit', compact('responsable', 'boarding_schools', 'boarders', 'users'));

        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ResponsableRequest $request, $id)
    {
        try {
            $this->responsable->update($request, $id);
            return redirect()->route('responsavel.index')->with('status', 'success')->with('message', 'Responsável alterado com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->responsable->destroy($id);
            return redirect()->route('responsavel.index')->with('status', 'success')->with('message', 'Responsável excluído com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }
}

resources/views/admin/responsables/_form.blade.php
<div class="new-responsable">
    <div class="form-group col-md-12">
        <label for="">Nome do responsável (*)</label>
        <input type="text" name="name" value="{{isset($responsable->name) ? $responsable->name : ''}}" required class="form-control name">
    </div>
    <div class="form-group col-md-6">
        <label for="">CPF (*)</label>
        <input type="text" name="cpf" value="{{isset($responsable->cpf) ? $responsable->cpf : ''}}" required class="cpf form-control">
    </div>
    <div class="form-group col-md-6">
        <label for="">RG (*)</label>
        <input type="number" name="rg" value="{{isset($responsable->rg) ? $responsable->rg : ''}}" required class="rg form-control">
    </div>
    <div class="form-group col-md-6">
        <label for="">Telefone (*)</label>
        <input type="text" name="phone" value="{{isset($responsable->phone) ? $responsable->phone : ''}}" required class="phone form-control">
    </div>
    <div class="form-group col-md-6">
        <label for="">E-mail (*)</label>
        <input type="email" name="email" value="{{isset($responsable->email) ? $responsable->email : ''}}" required class="email form-control">
    </div>
    <div class="form-group col-md-6">
        <label for="">Facebook (*)</label>
        <input type="text" name="facebook" value="{{isset($responsable->facebook) ? $responsable->facebook : ''}}" required class="facebook form-control">
    </div>
    <div class="form-group col-md-6">
        <label for="">Whatsapp (*)</label>
        <input type="text" name="whatsapp" value="{{isset($responsable->whatsapp) ? $responsable->whatsapp : ''}}" required class="phone form-control">
    </div>
</div>

resources/views/admin/responsables/_form_address.blade.php
<div class="box box-warning col-md-12">
    <h4><i class="fas fa-map-marked-alt mr10"></i>Endereço do responsável</h4>
    <div class="form-group col-md-12">
        <label for="">Cep (*)</label>
        <input type="text" id="cep" name="cep" required value="{{isset($responsable->address->cep) ? $responsable->address->cep : ''}}" class="cep form-control">
    </div>
    <div class="form-group col-md-9">
        <label for="">Rua (*)</label>
        <input type="text" id="street" name="street" value="{{isset($responsable->address->street) ? $responsable->address->street : ''}}" required class="street form-control">
    </div>
    <div class="form-group col-md-3">
        <label for="">Número (*)</label>
        <input type="text" id="number" name="number" value="{{isset($responsable->address->number) ? $responsable->address->number : ''}}" required class="number form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Bairro (*)</label>
        <input type="text" id="district" value="{{isset($responsable->address->district) ? $responsable->address->district : ''}}" name="district" required class="district form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Cidade (*)</label>
        <input type="text" id="city" name="city" value="{{isset($responsable->address->city) ? $responsable->address->city : ''}}" required class="city form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Estado (*)</label>
        <input type="text" id="state" name="state" value="{{isset($responsable->address->state) ? $responsable->address->state : ''}}" required class="state form-control">
    </div>
</div>

resources/views/admin/responsables/_form_boarding_or_boarder.blade.php
<div class="box box-success col-md-12">
    <h4><i class="fas fa-check mr10"></i>Atribuição</h4>
    <div class="form-group col-md-12">
        <label class="col-md-12" for="">Você deseja atribuir o responsável a um pensionato ou a um pensionista? (*)</label>

        <div class="col-md-6">
            <br>
            {{-- PENSIONISTA A QUEM O USUÁRIO É RESPONSAVEL --}}
            @isset($responsable->boarders[0])
                <label>Pensionistas a quem {{$responsable->name}} é responsável (*)</label>
                <br>
                @foreach($responsable->boarders as $boarder)
                <li>{{$boarder->name}}</li>
                    <br>
                @endforeach
                <br>
            @endisset
        </div>

        <div class="col-md-6">
            <br>
            {{-- PENSIONATOS A QUEM O USUÁRIO É RESPONSAVEL --}}
            @isset($responsable->boarding_school[0])
                <label>Pensionatos a quem {{$responsable->name}} é responsável (*)</label>
                <br>
                @foreach($responsable->boarding_school as $boarding)
                    <li>{{$boarding->name}}</li>
                    <br>
                @endforeach
                <br>
            @endisset
        </div>

        <br>
        <br>
        <div class="col-md-6">
            <i class="fas fa-user boarder"></i><label for="">Pensionista (*)</label>
            <input class="radio" type="radio" value="1" name="radio">
        </div>
        <div class="col-md-6">
            <i class="fas fa-home boarding"></i><label for="">Pensionato (*)</label>
            <input class="radio" type="radio" value="2" name="radio">
        </div>
    </div>
    <div class="form-group col-md-6 boarder-none none">
        <select name="boarder" class="form-control boarder">
            <option value="0" selected>Escolha um pensionista</option>
            @foreach($boarders as $boarder)
                <option value="{{$boarder->id}}">{{$boarder->name}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group col-md-6 boarding-none none ml-50">
        <select name="boarding" class="form-control boarding">
            <option value="0" selected>Escolha um pensionato</option>
            @foreach($boarding_schools as $boarding)
                <option value="{{$boarding->id}}">{{$boarding->name}}</option>
            @endforeach
        </select>
    </div>
</div>

<style>
.ml-50
{
    margin-left: 50% !important;
}
</style>

resources/views/admin/responsables/_form_users.blade.php
<div class="box box-warning col-md-12">
    <h4><i class="fas fa-check mr10"></i>Vincular Usuário</h4>
    <div class="form-group col-md-12">
        <label class="col-md-12" for="">A que usuário este responsável está vinculado? (*)</label>

        <div class="col-md-6">
            <br>
            {{-- USUÁRIO QUE O ESTE RESPONSÁVEL ESTÁ VINCULADO --}}
            @isset($users)
                <label>Usuários (*)</label>
                <select required class="form-control" name="user_id">
                    <option>Escolha um usuário</option>
                    @foreach($users as $user)
                        <option value="{{$user->id}}" {{isset($responsable->user[0]->id)  ? $responsable->user[0]->id == $user->id ? 'selected' : '' : ''}}>{{$user->name}}</option>
                    @endforeach
                </select>
            @endisset
        </div>
    </div>
</div>

resources/views/admin/responsables/create.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Novo</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Responsável</h4>
        <br>
        <form action="{{route('responsavel.store')}}" method="post">
            @csrf
            @include('admin.responsables._form')
            @include('admin.responsables._form_address')
            @include('admin.responsables._form_boarding_or_boarder')
            @include('admin.responsables._form_users')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('responsavel.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script src="{{asset('js/mask.js')}}"></script>
<script src="{{asset('js/cep.js')}}"></script>
<script>
$( document ).ready(function() {

    $('.radio').click(function() {

        $('.radio').on('change', function() {

            let value = $('input[name=radio]:checked').val();

            if(value == 1) {
                $('.boarder-none').show();
                $('.boarding-none').hide();

                $(".boarder").prop('required',true);
                $(".boarding").prop('required',false);
            }
            else if(value == 2){
                $('.boarding-none').show();
                $('.boarder-none').hide();

                $(".boarding").prop('required',true);
                $(".boarder").prop('required',false);
            }

        });
    });

});
</script>
@stop

resources/views/admin/responsables/edit.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Editar</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Responsável</h4>
        <br>
        <form action="{{route('responsavel.update', $responsable->id)}}" method="post">
            @method('put')
            @csrf
            @include('admin.responsables._form')
            @include('admin.responsables._form_address')
            @include('admin.responsables._form_boarding_or_boarder')
            @include('admin.responsables._form_users')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('responsavel.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script src="{{asset('js/mask.js')}}"></script>
<script src="{{asset('js/cep.js')}}"></script>
<script>
    $( document ).ready(function() {

        $('.radio').click(function() {

            $('.radio').on('change', function() {

                let value = $('input[name=radio]:checked').val();

                if(value == 1) {
                    $('.boarder-none').show();
                    $('.boarding-none').hide();

                    $(".boarder").prop('required',true);
                    $(".boarding").prop('required',false);
                }
                else if(value == 2){
                    $('.boarding-none').show();
                    $('.boarder-none').hide();

                    $(".boarding").prop('required',true);
                    $(".boarder").prop('required',false);
                }

            });
        });

    });
    </script>
@stop

resources/views/admin/responsables/index.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-user-shield"></i>Responsáveis</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
      <a href="{{route('responsavel.create')}}"><button class="btn btn-primary">Novo</button></a>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Nome</th>
                <th class="th-sm">Telefone</th>
                <th class="th-sm">Whatsapp</th>
                <th class="th-sm">Rua</th>
                <th class="th-sm">Nº</th>
                <th class="th-sm">Bairro</th>
                <th class="th-sm">Cidade</th>
                <th class="th-sm">Ações</th>
              </tr>
            </thead>
            <tbody>
            @foreach($responsables as $responsable)
              <tr>
                <td>{{$responsable->name}}</td>
                <td>{{$responsable->phone}}</td>
                <td>{{$responsable->whatsapp}}</td>
                <td>{{$responsable->address->street}}</td>
                <td>{{$responsable->address->number}}</td>
                <td>{{$responsable->address->district}}</td>
                <td>{{$responsable->address->city}}</td>
                <td>
                  <a href="{{route('responsavel.edit', $responsable->id)}}">
                    <button class="btn btn-success">
                      <i class="fas fa-edit"></i>
                    </button>
                  </a>
                  <button class="btn btn-danger js-btn-del"  data-item="{{$responsable->name}}" data-title="Responsável" data-route="{{route('responsavel.destroy', $responsable->id)}}"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop 

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop