routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => 'web'], function () {

        // 'middleware' => 'admin'
        Route::group(['prefix' => 'admin'], function () {

            Route::resource('/pensionato', 'BoardingSchoolController');
            Route::resource('/responsavel', 'ResponsableController');
            Route::resource('/pensionista', 'BoarderController');
            Route::resource('/quartos', 'BedroomController');
            Route::resource('/contrato', 'ContractController');
            Route::resource('/gastos-mensais', 'MonthlyBillController');
            Route::resource('/melhorias', 'ImprovementController');
            Route::resource('/funcionario', 'EmployeeController');
            Route::resource('/tarefas', 'TaskController');
            Route::resource('/contato', 'ContactController');
            Route::resource('/usuario', 'UserController');
            Route::resource('/regras', 'RuleController');

            Route::get('/melhorias-completas', 'ImprovementController@completed')->name('melhorias.completed');
            Route::get('/melhorias/to-complete/{id}', 'ImprovementController@complete')->name('melhorias.complete');
            Route::get('/melhorias-aprovadas', 'ImprovementController@approved')->name('melhorias.approved');
            Route::get('/melhorias/nao/aprovadas', 'ImprovementController@desaproved')->name('melhorias.desaproved');
            Route::get('/melhorias/to-approve/{id}', 'ImprovementController@approve')->name('melhorias.to.approve');
            Route::post('/melhorias/to-desaprove/{id}', 'ImprovementController@desapprove')->name('melhorias.to.desapprove');
            Route::get('/melhorias/check-duplication/{name}', 'ImprovementController@checkDuplication')->name('melhorias.check-duplication');

            Route::get('/home/pensionato', 'BoardingSchoolController@home')->name('boarding.home');

            Route::get('/configuracoes', 'ConfigController@create')->name('system.config');
            Route::get('/configuracoes/show/', 'ConfigController@show')->name('system.config.show');
            Route::post('/configuracoes/store', 'ConfigController@store')->name('system.config.store');
            Route::get('/configuracoes/edit/{id}', 'ConfigController@edit')->name('system.config.edit');
            Route::put('/configuracoes/update/{id}', 'ConfigController@update')->name('system.config.update');

            Route::get('/mensalidades', 'PaymentController@index')->name('payment.index');
            Route::get('/mensalidades/show/{id}', 'PaymentController@show')->name('payment.show');
            Route::get('/gerar', 'PaymentController@generate')->name('payment.generate');
        });


        //MIDDLEWARE PENSIONISTA
        Route::group(['middleware' => 'boarder', 'prefix' => 'pensionista'], function () {

        });

        //'middleware' => 'employee',
        //MIDDLEWARE FUNCIONÁRIO
        Route::group(['prefix' => 'funcionario'], function () {
            Route::get('/tarefas', 'EmployeeController@listTasksOfEmployee')->name('tasks.employee');
        });



        Route::get('/home', 'DashboardController@index')->name('home');
        Route::get('/modal', 'Controller@modal')->name('modal');
        Route::get('/modal/improvement', 'Controller@modalImprovement')->name('modal.improvement');
        Route::get('/modal/completed', 'Controller@modalCompleted')->name('modal.completed');
    });

});

Auth::routes();
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', function () {
    return redirect('/login');
});

app/Models/Improvement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Improvement extends Model
{
    protected $fillable = ['title', 'approved', 'completed', 'votes', 'reason', 'status', 'users_id'];

    public $timestamps = false;
}

app/Http/Controllers/ImprovementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ImprovementRequest;
use App\Repositories\ImprovementRepository;

class ImprovementController extends Controller
{
    private $improvement;

    public function __construct()
    {
        $this->improvement = new ImprovementRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $data = $this->improvement->index($request);
            $improvements = $data[1];
            $boarder= $data[0];

            return view('admin.improvements.index', compact('improvements', 'boarder'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('admin.improvements.create');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ImprovementRequest $request)
    {
        try {
         $this->improvement->store($request);
            return redirect()->route('melhorias.index')->with('status', 'success')->with('message', 'Melhoria criada com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $improvement = $this->improvement->edit($id);
            return view('admin.improvements.edit', compact('improvement'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ImprovementRequest $request, $id)
    {
        try {
            $this->improvement->update($request, $id);
            return redirect()->route('melhorias.index')->with('status', 'success')->with('message', 'Melhoria alterada com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->improvement->destroy($id);
            return redirect()->route('melhorias.index')->with('status', 'success')->with('message', 'Melhoria excluída com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    public function desaproved()
    {
        try {
            $improvements = $this->improvement->desaproved();
            return view('admin.improvements.not-approved', compact('improvements'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }

    }

    public function desapprove(Request $request, $id)
    {
        return $this->improvement->desapprove($request, $id);
    }

    public function approved()
    {
        try {
            $improvements = $this->improvement->approved();
            return view('admin.improvements.approved', compact('improvements'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    public function approve($id)
    {
        return $this->improvement->approve($id);
    }

    public function completed()
    {
        try {
            $improvements = $this->improvement->completed();
            return view('admin.improvements.completed', compact('improvements'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    public function complete($id)
    {
        $this->improvement->complete($id);
    }

    public function checkDuplication($name)
    {
        return $this->improvement->checkDuplication($name);
    }
}

resources/views/admin/improvements/_form.blade.php
<div class="new-contract">
    <div class="form-group col-md-12">
        <label for="">Melhoria (*)</label>
        <input type="text" name="title" id="title" class="form-control" required value="{{isset($improvement->title) ? $improvement->title : ''}}">
    </div>
</div>

resources/views/admin/improvements/approved.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas file-signature"></i>Melhorias aprovadas</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
        <a href="{{route('melhorias.create')}}"><button class="btn btn-primary mt-10">Novo</button></a>
        <a href="{{route('melhorias.index')}}"><button class="btn btn-primary mt-10">Todas</button></a>
        <a href="{{route('melhorias.approved')}}"><button class="btn btn-primary mt-10">Aprovados</button></a>
        <a href="{{route('melhorias.desaproved')}}"><button class="btn btn-primary mt-10">Não aprovadas</button></a>
        <a href="{{route('melhorias.completed')}}"><button class="btn btn-primary mt-10">Completas</button></a>
        <br>
        <h3>Fundo xx,xx</h3>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Melhoria</th>
                <th class="th-sm">Ações</th>
              </tr>
            </thead>
            <tbody>
            @foreach($improvements as $improvement)
              <tr>
                <td>{{$improvement->title}}</td>
                <td>
                  <a href="{{route('melhorias.edit', $improvement->id)}}">
                    <button class="btn btn-success">
                      <i class="fas fa-edit"></i>
                    </button>
                  </a>
                  <button class="btn btn-danger js-btn-del" data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.destroy', $improvement->id)}}"><i class="fas fa-trash"></i></button>
                  <button class="btn btn-success js-btn-completed "data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.complete', $improvement->id)}}"><i class="fas fa-check-double"></i></button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop 

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop

resources/views/admin/improvements/check-duplication.blade.php
<div class="modal" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="conteudo-modal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Possível duplicação de melhoria</h4>
                </div>
                <div class="modal-body">
                    <p>Por favor verifique se sua solicitação de melhoria, já consta em outra solicitação</p>
                    <div class="list">
                        <!-- Listar collections retornadas no ajax -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success continue">Continuar</button>
                    <button type="button" class="btn btn-danger" class="close" data-dismiss="modal">Cancelar</button>
                </div>      
            </div>
        </div>
    </div>
</div>

resources/views/admin/improvements/completed.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas file-signature"></i>Melhorias completas</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
        <a href="{{route('melhorias.create')}}"><button class="btn btn-primary mt-10">Novo</button></a>
        <a href="{{route('melhorias.index')}}"><button class="btn btn-primary mt-10">Todas</button></a>
        <a href="{{route('melhorias.approved')}}"><button class="btn btn-primary mt-10">Aprovados</button></a>
        <a href="{{route('melhorias.desaproved')}}"><button class="btn btn-primary mt-10">Não aprovadas</button></a>
        <a href="{{route('melhorias.completed')}}"><button class="btn btn-primary mt-10">Completas</button></a>
        <br>
        <h3>Fundo xx,xx</h3>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Melhoria</th>
                <th class="th-sm">Ações</th>
              </tr>
            </thead>
            <tbody>
            @foreach($improvements as $improvement)
              <tr>
                <td>{{$improvement->title}}</td>
                <td>
                  <button class="btn btn-danger js-btn-del" data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.destroy', $improvement->id)}}"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop 

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop

resources/views/admin/improvements/create.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Novo</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    @include('admin.improvements.check-duplication')
    <div class="box box-primary col-md-12 mt10">
        <h4>Melhoria</h4>
        <br>
        <form action="{{route('melhorias.store')}}" class="form-class" method="post">
            @csrf
            @include('admin.improvements._form')
            <div class="col-md-3">
                <button type="button" class="w78 btn btn-success submit" data-toggle="modal" data-target="#myModal"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('melhorias.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop
@section('js')
<script>
    $(document).ready(function() {
        $("#myModal").remove();
        $('#myModal2').prop('id', 'myModal');
    });

    $('.continue').click(function (){
        $( ".form-class" ).submit();
    });

    $('#title').keypress(function(event){
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13'){
            event.preventDefault();
            checkDuplication();
        }
    });

    $('.submit').click(function (){
        checkDuplication();
    });

    function checkDuplication() {
        let name = $('#title').val();
        let route = '/admin/melhorias/check-duplication/'+name;

        $.ajax({
            type: 'GET',
            url: route,
            success: function (data){
                if(!data[0]){
                    $( ".form-class" ).submit();
                } else {
                    $('#myModal2').show();
                    for (var i = 0; i < data.length; i++) {
                        $(".list").append("<p>"+data[i].title+"</p>");
                    }
                }
            }
        });
    }
</script>
@stop

resources/views/admin/improvements/edit.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Editar</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Melhoria</h4>
        <form action="{{route('melhorias.update', $improvement->id)}}" method="post">
            @method('put')
            @csrf
            @include('admin.improvements._form')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('melhorias.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

resources/views/admin/improvements/index.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas file-signature"></i>Melhorias</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
        <a href="{{route('melhorias.create')}}"><button class="btn btn-primary mt-10">Novo</button></a>
        <a href="{{route('melhorias.approved')}}"><button class="btn btn-primary mt-10">Aprovados</button></a>
        <a href="{{route('melhorias.desaproved')}}"><button class="btn btn-primary mt-10">Não aprovadas</button></a>
        <a href="{{route('melhorias.completed')}}"><button class="btn btn-primary mt-10">Completas</button></a>
        <br>
        <h3>Fundo xx,xx</h3>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Melhoria</th>
                <th class="th-sm">Status</th>
                <th class="th-sm">Completo</th>
                <th class="th-sm">Ações</th>
              </tr>
            </thead>
            <tbody>
            @foreach($improvements as $improvement)
              <tr>
                <td>{{$improvement->title}}</td>
                <td>{{($improvement->approved == 0) ? 'Não aprovado' : 'Aprovado'}}</td>
                <td>{{($improvement->completed == 0) ? 'Não' : 'Sim'}}</td>
                <td>
                  <a href="{{route('melhorias.edit', $improvement->id)}}">
                    <button class="btn btn-success">
                      <i class="fas fa-edit"></i>
                    </button>
                  </a>
                  <button class="btn btn-danger js-btn-del" data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.destroy', $improvement->id)}}"><i class="fas fa-trash"></i></button>
                  @if($improvement->approved == 0)
                    <button class="btn btn-success js-btn-improvement" {{(($improvement->votes*60)/100) == (($boarder*60)/100) ? '' : 'disabled'}} data-improvement="aprovar" data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.to.approve', $improvement->id)}}">
                      <i class="fas fa-check"></i>
                    </button>
                    <button class="btn btn-danger js-btn-improvement" {{(($improvement->votes*60)/100) == (($boarder*60)/100) ? '' : 'disabled'}} data-improvement="rejeitar" data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.to.desapprove', $improvement->id)}}">
                      <i class="fas fa-times"></i>
                    </button>
                  @endif
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop 

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop

resources/views/admin/improvements/not-approved.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas file-signature"></i>Melhorias não aprovadas</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
        <a href="{{route('melhorias.create')}}"><button class="btn btn-primary mt-10">Novo</button></a>
        <a href="{{route('melhorias.index')}}"><button class="btn btn-primary mt-10">Todas</button></a>
        <a href="{{route('melhorias.approved')}}"><button class="btn btn-primary mt-10">Aprovados</button></a>
        <a href="{{route('melhorias.desaproved')}}"><button class="btn btn-primary mt-10">Não aprovadas</button></a>
        <a href="{{route('melhorias.completed')}}"><button class="btn btn-primary mt-10">Completas</button></a>
        <br>
        <h3>Fundo xx,xx</h3>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Melhoria</th>
                <th class="th-sm">Motivo da rejeição</th>
                <th class="th-sm">Ações</th>
              </tr>
            </thead>
            <tbody>
            @foreach($improvements as $improvement)
              <tr>
                <td>{{$improvement->title}}</td>
                <td>{{$improvement->reason}}</td>
                <td>
                  <a href="{{route('melhorias.edit', $improvement->id)}}">
                    <button class="btn btn-success">
                      <i class="fas fa-edit"></i>
                    </button>
                  </a>
                  <button class="btn btn-danger js-btn-del" data-item="{{$improvement->title}}" data-title="Melhoria" data-route="{{route('melhorias.destroy', $improvement->id)}}"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop 

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop