routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => 'web'], function () {

        // 'middleware' => 'admin'
        Route::group(['prefix' => 'admin'], function () {

            Route::resource('/pensionato', 'BoardingSchoolController');
            Route::resource('/responsavel', 'ResponsableController');
            Route::resource('/pensionista', 'BoarderController');
            Route::resource('/quartos', 'BedroomController');
            Route::resource('/contrato', 'ContractController');
            Route::resource('/gastos-mensais', 'MonthlyBillController');
            Route::resource('/melhorias', 'ImprovementController');
            Route::resource('/funcionario', 'EmployeeController');
            Route::resource('/tarefas', 'TaskController');
            Route::resource('/contato', 'ContactController');
            Route::resource('/usuario', 'UserController');
            Route::resource('/regras', 'RuleController');

            Route::get('/melhorias-completas', 'ImprovementController@completed')->name('melhorias.completed');
            Route::get('/melhorias/to-complete/{id}', 'ImprovementController@complete')->name('melhorias.complete');
            Route::get('/melhorias-aprovadas', 'ImprovementController@approved')->name('melhorias.approved');
            Route::get('/melhorias/nao/aprovadas', 'ImprovementController@desaproved')->name('melhorias.desaproved');
            Route::get('/melhorias/to-approve/{id}', 'ImprovementController@approve')->name('melhorias.to.approve');
            Route::post('/melhorias/to-desaprove/{id}', 'ImprovementController@desapprove')->name('melhorias.to.desapprove');
            Route::get('/melhorias/check-duplication/{name}', 'ImprovementController@checkDuplication')->name('melhorias.check-duplication');

            Route::get('/home/pensionato', 'BoardingSchoolController@home')->name('boarding.home');

            Route::get('/configuracoes', 'ConfigController@create')->name('system.config');
            Route::get('/configuracoes/show/', 'ConfigController@show')->name('system.config.show');
            Route::post('/configuracoes/store', 'ConfigController@store')->name('system.config.store');
            Route::get('/configuracoes/edit/{id}', 'ConfigController@edit')->name('system.config.edit');
            Route::put('/configuracoes/update/{id}', 'ConfigController@update')->name('system.config.update');

            Route::get('/mensalidades', 'PaymentController@index')->name('payment.index');
            Route::get('/mensalidades/show/{id}', 'PaymentController@show')->name('payment.show');
            Route::get('/gerar', 'PaymentController@generate')->name('payment.generate');
        });


        //MIDDLEWARE PENSIONISTA
        Route::group(['middleware' => 'boarder', 'prefix' => 'pensionista'], function () {

        });

        //'middleware' => 'employee',
        //MIDDLEWARE FUNCIONÁRIO
        Route::group(['prefix' => 'funcionario'], function () {
            Route::get('/tarefas', 'EmployeeController@listTasksOfEmployee')->name('tasks.employee');
        });



        Route::get('/home', 'DashboardController@index')->name('home');
        Route::get('/modal', 'Controller@modal')->name('modal');
        Route::get('/modal/improvement', 'Controller@modalImprovement')->name('modal.improvement');
        Route::get('/modal/completed', 'Controller@modalCompleted')->name('modal.completed');
    });

});

Auth::routes();
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', function () {
    return redirect('/login');
});

app/Models/BoardingSchool.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BoardingSchool extends Model
{
    protected $fillable = ['name', 'status', 'responsables_id'];

    protected $table = 'boarding_school';

    public function responsable()
    {
        return $this->belongsTo('App\Models\Responsable', 'responsables_id')->where('status', 1);
    }

    public function address()
    {
        return $this->belongsTo('App\Models\Address', 'addresses_id')->where('status', 1);
    }

    public function rules()
    {
        return $this->hasMany('App\Models\Rule', 'boarding_school_id')->where('status', 1);
    }

    public function bedrooms()
    {
        return $this->belongsToMany('App\Models\Bedroom', 'boarding_school_has_bedrooms', 'bedrooms_id', 'boarding_school_id')->where('status', 1);
    }

    public function contact(){
        return $this->hasMany('App\Models\Contact');
    }
}

app/Http/Controllers/BoardingSchoolController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\BoardingSchoolRequest;
use App\Repositories\BoardingSchoolRepository;

class BoardingSchoolController extends Controller
{
    private $boarder;

    public function __construct()
    {
        $this->boarder = new BoardingSchoolRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $boarding_schools = $this->boarder->index();
            return view('admin.boarding_school.index', compact('boarding_schools'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    public function home(Request $request)
    {
        try {

            if(\Auth::user()->login == 0 && \Auth::user()->role == 'administrador') {
                return redirect()->route('system.config');
            }

            $responsable = $this->boarder->home();
            return view('admin.boarding_school.home', compact('responsable'));

        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $responsables = $this->boarder->create();
            return view('admin.boarding_school.create', compact('responsables'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BoardingSchoolRequest $request)
    {
        try {
            $boarding_school = $this->boarder->store($request);
            return redirect()->route('pensionato.index')->with('status', 'success')->with('message', 'Pensionato criado com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        try {
            parent::session($request, $id);
            return redirect()->route('home');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data = $this->boarder->edit($id);
            $boarding_school = $data[0];
            $responsables = $data[1];

            return view('admin.boarding_school.edit', compact('boarding_school', 'responsables'));

        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BoardingSchoolRequest $request, $id)
    {
        try {
            return $this->boarder->update($request, $id);
            return redirect()->route('pensionato.index')->with('status', 'success')->with('message', 'Pensionato alterado com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            return $this->boarder->destroy($id);
            return redirect()->route('pensionato.index')->with('status', 'success')->with('message', 'Pensionato excluído com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }
}

resources/views/admin/boarding_school/_form-address-boarding.blade.php
<div class="box box-warning col-md-12">
    <h4><i class="fas fa-map-marked-alt mr10"></i>Endereço</h4>
    <div class="form-group col-md-12">
        <label for="">Cep (*)</label>
        <input required type="text" id="cep" name="cep" value="{{isset($boarding_school->address->cep) ? $boarding_school->address->cep : ''}}" class="cep form-control">
    </div>
    <div class="form-group col-md-9">
        <label for="">Rua (*)</label>
        <input required type="text" id="street" name="street" value="{{isset($boarding_school->address->street) ? $boarding_school->address->street : ''}}" class="form-control">
    </div>
    <div class="form-group col-md-3">
        <label for="">Número (*)</label>
        <input required type="text" id="number" name="number" value="{{isset($boarding_school->address->number) ? $boarding_school->address->number : ''}}" class="form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Bairro (*)</label>
        <input required type="text" id="district" name="district" value="{{isset($boarding_school->address->district) ? $boarding_school->address->district : ''}}" class="form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Cidade (*)</label>
        <input required type="text" id="city" name="city" value="{{isset($boarding_school->address->city) ? $boarding_school->address->city : ''}}" class="form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Estado (*)</label>
        <input required type="text" id="state" name="state" value="{{isset($boarding_school->address->state) ? $boarding_school->address->state : ''}}" class="form-control">
    </div>
</div>

resources/views/admin/boarding_school/_form-address-responsable.blade.php
<div class="box box-danger col-md-12">
    <h4><i class="fas fa-map-marked-alt mr10"></i>Endereço do responsável</h4>
    <div class="form-group col-md-12">
        <label for="">Cep (*)</label>
        <input type="text" id="cep2" name="cep_responsable" class="cep form-control">
    </div>
    <div class="form-group col-md-9">
        <label for="">Rua (*)</label>
        <input type="text" id="street2" name="street_responsable" class="street form-control">
    </div>
    <div class="form-group col-md-3">
        <label for="">Número (*)</label>
        <input type="text" id="number2" name="number_responsable" class="number form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Bairro (*)</label>
        <input type="text" id="district2" name="district_responsable" class="district form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Cidade (*)</label>
        <input type="text" id="city2" name="city_responsable" class="city form-control">
    </div>
    <div class="form-group col-md-4">
        <label for="">Estado (*)</label>
        <input type="text" id="state2" name="state_responsable" class="state form-control">
    </div>
</div>

resources/views/admin/boarding_school/_form-responsable.blade.php
<div class="box box-success col-md-12">
    <h4><i class="fas fa-user-shield mr10"></i>Responsável</h4>
    <div class="form-group">
        <label for="">Selecione um responsável existente ou adicione ou novo (*)</label>
        <select required class="form-control responsable" name="responsable_id">
            <option>Selecione</option>
            <option value="0">Novo</option>
            @foreach($responsables as $responsable)
                @isset($boarding_school)
                    <option {{($boarding_school->responsable->id == $responsable->id ? 'selected' : '')}} value="{{$responsable->id}}">{{$responsable->name}}</option>
                @endisset
                @empty($boarding_school)
                    <option value="{{$responsable->id}}">{{$responsable->name}}</option>
                @endempty
            @endforeach
        </select>
    </div>
    <div class="new-responsable none">
        <div class="form-group col-md-12">
            <label for="">Nome do responsável (*)</label>
            <input type="text" name="responsable_name" class="form-control responsable_name">
        </div>
        <div class="form-group col-md-6">
            <label for="">CPF (*)</label>
            <input type="text" name="cpf" class="cpf form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="">RG (*)</label>
            <input type="number" name="rg" class="rg form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="">Telefone (*)</label>
            <input type="text" name="phone" class="phone form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="">E-mail (*)</label>
            <input type="email" name="email" class="email form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="">Facebook (*)</label>
            <input type="text" name="facebook" class="facebook form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="">Whatsapp</label>
            <input type="text" name="whatsapp" class="phone form-control">
        </div>

        @include('admin.boarding_school._form-address-responsable')
    </div>
</div>

resources/views/admin/boarding_school/_form.blade.php
<div class="form-group col-md-12">
    <label for="">Nome do pensionato (*)</label>
    <input type="text" name="name" value="{{isset($boarding_school->name) ? $boarding_school->name : ''}}" class="form-control">
</div>

resources/views/admin/boarding_school/create.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Novo</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Pensionato</h4>
        <br>
        <form action="{{route('pensionato.store')}}" method="post">
            @csrf
            @include('admin.boarding_school._form')
            @include('admin.boarding_school._form-address-boarding')
            @include('admin.boarding_school._form-responsable')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('pensionato.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script src="{{asset('js/mask.js')}}"></script>
<script src="{{asset('js/cep.js')}}"></script>
<script>
    $( document ).ready(function() {
        $('.responsable').change(function(){
            var valor = $('.responsable').val();

            if(valor == 0) {
                $('.new-responsable').show();
            }
            else
            {
                $('.new-responsable').hide();
            }

        });
    });
</script>
@stop

resources/views/admin/boarding_school/edit.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Novo</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Pensionato</h4>
        <br>
        <form action="{{route('pensionato.update', $boarding_school->id)}}" method="post">
            @method('put')
            @csrf
            @include('admin.boarding_school._form')
            @include('admin.boarding_school._form-address-boarding')
            @include('admin.boarding_school._form-responsable')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('pensionato.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script src="{{asset('js/mask.js')}}"></script>
<script src="{{asset('js/cep.js')}}"></script>
<script>
    $( document ).ready(function() {

        $('.responsable').change(function(){
            var valor = $('.responsable').val();

            if(valor == 0) {
                $('.new-responsable').show();
                $(".responsable_name").prop('required',true);
                $(".cpf").prop('required',true);
                $(".rg").prop('required',true);
                $(".phone").prop('required',true);
                $(".email").prop('required',true);
                $(".facebook").prop('required',true);
                $(".cep").prop('required',true);
                $(".number").prop('required',true);
                $(".street").prop('required',true);
                $(".district").prop('required',true);
                $(".city").prop('required',true);
                $(".state").prop('required',true);
            }
            else
            {
                $('.new-responsable').hide();
                $(".responsable_name").prop('required',false);
                $(".cpf").prop('required',false);
                $(".rg").prop('required',false);
                $(".phone").prop('required',false);
                $(".email").prop('required',false);
                $(".facebook").prop('required',false);
                $(".cep").prop('required',false);
                $(".number").prop('required',false);
                $(".street").prop('required',false);
                $(".district").prop('required',false);
                $(".city").prop('required',false);
                $(".state").prop('required',false);
            }

        });

    });
</script>
@stop

resources/views/admin/boarding_school/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{asset('css/boarding_school.css')}}">
    <title>Gerencia Pensionato</title>
</head>
<body>
    <div class="mt-15">
        <h1 class="text-center mt-5">Seja Bem-vindo(a) {{isset($responsable->name) ? $responsable->name : $user->name }}</h1>
        <div  class="box-max">
            @isset($responsable->boarding_school)
                @foreach($responsable->boarding_school as $boarding_school)
                    <div class="box-home border mr10 mt-5 box-max">
                        <a href="{{route('pensionato.show', $boarding_school->id)}}">
                            <i class="fas fa-home fa-5x" title="{{$boarding_school->name}}"></i>
                        </a>
                    </div>
                @endforeach
            @endisset
            {{-- <div class="box-home border mt-5 mr10 box-max">
                <a href="">
                    <i class="fas fa-home fa-5x"></i>
                </a>
            </div>
            <div class="box-home border mr10 mt-5 box-max">
                <a href="">
                    <i class="fas fa-home fa-5x"></i>
                </a>
            </div>
            <div class="box-home border mr10 mt-5 box-max">
                <a href="">
                    <i class="fas fa-home fa-5x"></i>
                </a>
            </div> --}}
            <div class="box-home box-max border mt-5 ">
                <a href="{{route('pensionato.create')}}">
                    <i class="fas fa-plus fa-5x" title="Novo"></i>
                </a>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/admin/boarding_school/index.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-home"></i>Pensionatos</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
        <a href="{{route('pensionato.create')}}"><button class="btn btn-primary">Novo</button></a>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Pensionato
                </th>
                <th class="th-sm">Responsável
                </th>
                <th class="th-sm">Rua
                </th>
                    <th class="th-sm">Nº
                </th>
                <th class="th-sm">Bairro
                </th>
                <th class="th-sm">Cidade
                </th>
                <th class="th-sm">Ações
                </th>
              </tr>
            </thead>
            <tbody>
            @foreach($boarding_schools as $boarding_school)
              <tr>
                <td>{{$boarding_school->name}}</td>
                <td>{{$boarding_school->responsable->name}}</td>
                <td>{{$boarding_school->address->street}}</td>
                <td>{{$boarding_school->address->number}}</td>
                <td>{{$boarding_school->address->district}}</td>
                <td>{{$boarding_school->address->city}}</td>
                <td>
                  <a href="{{route('pensionato.edit', $boarding_school->id)}}">
                    <button class="btn btn-success">
                      <i class="fas fa-edit"></i>
                    </button>
                  </a>
                  <button class="btn btn-danger js-btn-del"  data-item="{{$boarding_school->name}}" data-title="Pensionato" data-route="{{route('pensionato.destroy', $boarding_school->id)}}"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop 

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop