routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {

    Route::group(['middleware' => 'web'], function () {

        // 'middleware' => 'admin'
        Route::group(['prefix' => 'admin'], function () {

            Route::resource('/pensionato', 'BoardingSchoolController');
            Route::resource('/responsavel', 'ResponsableController');
            Route::resource('/pensionista', 'BoarderController');
            Route::resource('/quartos', 'BedroomController');
            Route::resource('/contrato', 'ContractController');
            Route::resource('/gastos-mensais', 'MonthlyBillController');
            Route::resource('/melhorias', 'ImprovementController');
            Route::resource('/funcionario', 'EmployeeController');
            Route::resource('/tarefas', 'TaskController');
            Route::resource('/contato', 'ContactController');
            Route::resource('/usuario', 'UserController');
            Route::resource('/regras', 'RuleController');

            Route::get('/melhorias-completas', 'ImprovementController@completed')->name('melhorias.completed');
            Route::get('/melhorias/to-complete/{id}', 'ImprovementController@complete')->name('melhorias.complete');
            Route::get('/melhorias-aprovadas', 'ImprovementController@approved')->name('melhorias.approved');
            Route::get('/melhorias/nao/aprovadas', 'ImprovementController@desaproved')->name('melhorias.desaproved');
            Route::get('/melhorias/to-approve/{id}', 'ImprovementController@approve')->name('melhorias.to.approve');
            Route::post('/melhorias/to-desaprove/{id}', 'ImprovementController@desapprove')->name('melhorias.to.desapprove');
            Route::get('/melhorias/check-duplication/{name}', 'ImprovementController@checkDuplication')->name('melhorias.check-duplication');

            Route::get('/home/pensionato', 'BoardingSchoolController@home')->name('boarding.home');

            Route::get('/configuracoes', 'ConfigController@create')->name('system.config');
            Route::get('/configuracoes/show/', 'ConfigController@show')->name('system.config.show');
            Route::post('/configuracoes/store', 'ConfigController@store')->name('system.config.store');
            Route::get('/configuracoes/edit/{id}', 'ConfigController@edit')->name('system.config.edit');
            Route::put('/configuracoes/update/{id}', 'ConfigController@update')->name('system.config.update');

            Route::get('/mensalidades', 'PaymentController@index')->name('payment.index');
            Route::get('/mensalidades/show/{id}', 'PaymentController@show')->name('payment.show');
            Route::get('/gerar', 'PaymentController@generate')->name('payment.generate');
        });


        //MIDDLEWARE PENSIONISTA
        Route::group(['middleware' => 'boarder', 'prefix' => 'pensionista'], function () {

        });

        //'middleware' => 'employee',
        //MIDDLEWARE FUNCIONÁRIO
        Route::group(['prefix' => 'funcionario'], function () {
            Route::get('/tarefas', 'EmployeeController@listTasksOfEmployee')->name('tasks.employee');
        });



        Route::get('/home', 'DashboardController@index')->name('home');
        Route::get('/modal', 'Controller@modal')->name('modal');
        Route::get('/modal/improvement', 'Controller@modalImprovement')->name('modal.improvement');
        Route::get('/modal/completed', 'Controller@modalCompleted')->name('modal.completed');
    });

});

Auth::routes();
Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', function () {
    return redirect('/login');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['description'];

    public function employee() {
        return $this->belongsTo('App\Models\Employee', 'employees_id');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\TaskRequest;
use App\Repositories\TaskRepository;

class TaskController extends Controller
{
    private $task;

    public function __construct()
    {
        $this->task = new TaskRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $tasks = $this->task->index();
            return view('admin.tasks.index', compact('tasks'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $employees = $this->task->create();
            return view('admin.tasks.create', compact('employees'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskRequest $request)
    {
        try {
            $this->task->store($request);
            return redirect()->route('tarefas.index')->with('status', 'success')->with('message', 'Tarefa criada com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data = $this->task->edit($id);
            $task = $data[0];
            $employees = $data[1];

            return view('admin.tasks.edit', compact('task', 'employees'));
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TaskRequest $request, $id)
    {
        try {
            $this->task->update($request, $id);
            return redirect()->route('tarefas.index')->with('status', 'success')->with('message', 'Tarefa alterada com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->task->destroy($id);
            return redirect()->route('tarefas.index')->with('status', 'success')->with('message', 'Tarefa excluída com sucesso!');
        } catch (\Exception $e) {
            return redirect()->back()->with('status', 'danger')->with('message', 'Erro. Tente novamente.');
        }
    }
}

resources/views/admin/tasks/_form.blade.php
<div class="form-group col-md-12">
    <label for="">Descrição (*)</label>
    <textarea class="form-control" name="description">{{(isset($task->description) ? $task->description : '')}}</textarea>
</div>
<div class="form-group col-md-12">
    <label for="">Funcionário (*)</label>
    <select name="employees_id" class="form-control">
        <option>Selecione um funcionário</option>
        @foreach($employees as $employee)
            <option value="{{$employee->id}}" {{ (isset($task) ? ($task->employees_id == $employee->id ? 'selected' : '') : '') }}>{{$employee->name}}</option>
        @endforeach
    </select>
</div>

resources/views/admin/tasks/create.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Novo</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Tarefas</h4>
        <br>
        <form action="{{route('tarefas.store')}}" method="post">
            @csrf
            @include('admin.tasks._form')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('tarefas.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

resources/views/admin/tasks/edit.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas fa-external-link-alt"></i>Editar</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="box box-primary col-md-12 mt10">
        <h4>Tarefas</h4>
        <form action="{{route('tarefas.update', $task->id)}}" method="post">
            @method('put')
            @csrf
            @include('admin.tasks._form')
            <div class="col-md-3">
                <button type="submit" class="w78 btn btn-success"><i class="far fa-save fa-2x"></i><br>Salvar</button>
                <a href="{{route('tarefas.index')}}"><button type="button" class="w78 btn btn-danger"><i class="fas fa-times fa-2x"></i><br>Cancelar</button></a>
            </div>
        </form>
    </div>
@stop

resources/views/admin/tasks/index.blade.php
@extends('adminlte::page')

@section('title', 'Gerencia Pensionato')

@section('content_header')
    <h1><i class="fas file-signature"></i>Tarefas</h1>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/app-boarding.css')}}">
@stop
@section('content')
    <div class="col-md-12 mt10">
        <a href="{{route('tarefas.create')}}"><button class="btn btn-primary mt-10">Novo</button></a>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th class="th-sm">Descrição</th>
                <th class="th-sm">Funcionário</th>
                <th class="th-sm">Ações</th>
              </tr>
            </thead>
            <tbody>
            @foreach($tasks as $task)
              <tr>
                <td>{!!$task->description!!}</td>
                <td>{{$task->employee->name}}</td>
                <td>
                  <a href="{{route('tarefas.edit', $task->id)}}">
                    <button class="btn btn-success">
                      <i class="fas fa-edit"></i>
                    </button>
                  </a>
                  <button class="btn btn-danger js-btn-del"  data-item="{{$task->description}}" data-title="Contrato" data-route="{{route('tarefas.destroy', $task->id)}}"><i class="fas fa-trash"></i></button>
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
    </div>
@stop

@section('js')
<script src="{{asset('js/boarding.js')}}"></script>
@stop